### ISSUE TITLE
Use other library for compression

### ISSUE THREAD

**Issue by anyRandomHuman** [problemsalved/balatro_save_editor#1]
My zlib version was too old and does not support the compress method taking the 'wbits' argument.
And removing that causes the decompressed then compressed data to be different than the original.
Attempts to update the lib failed.
So i'd like to ask if there is another way to decompress the data?

**Comment by abahr35** [comment]
your python could be on a version lower than the repo was made on. Worked for me on python 3.11

**Comment by anyRandomHuman** [comment]
OK, I switched to 3.11 and it worked. Sorry to bother.
